export const arr = [
  {
    id: 800,
    title: "Q&A within the challenge hubs",
    votes: 1,
    tag: "feature",
    comments: [],
    status: "planned",
    feedback: "Challenge-specific Q&A would make for easy reference.",
  },
  {
    id: 500,
    title: "Add tags for solutions",
    votes: 44,
    tag: "enhancement",
    comments: [],
    status: "inProgress",
    feedback: "Stay updated on comments and solutions other people post.",
  },
  {
    id: 300,
    title: "Add a dark theme option",
    votes: 4,
    tag: "feature",
    comments: [],
    status: "planned",
    feedback:
      "It would help people with light sensitivities and who prefer dark mode.",
  },
  {
    id: 200,
    title: "Allow image/video upload",
    votes: 5,
    tag: "enhancement",
    comments: [],
    status: "live",
    feedback: "Images and screencasts can enhance comments on solutions.",
  },
  {
    id: 100,
    title: "Preview images not loading",
    votes: 43,
    tag: "bug",
    comments: [],
    status: "live",
    feedback: "Stay updated on comments and solutions other people post.",
  },
  {
    id: 55,
    title: "Random Ux",
    votes: 23,
    tag: "ux",
    comments: [],
    status: "inProgress",
    feedback: "Stay updated on comments and solutions other people post.",
  },
];
